- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Deploy application
  shell: |
    docker-compose down
    docker-compose up -d --build
  args:
    chdir: /home/ubuntu/YourProject
