---
- name: Ensure app directory exists
  file:
    path: /opt/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy application files to EC2 instance
  copy:
    src: ../app/
    dest: /opt/app/
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  notify: Restart Gunicorn

- name: Ensure Python 3 venv package is installed
  apt:
    name: python3-venv
    state: present
  become: true

- name: Create virtual environment
  command: python3 -m venv /opt/app/venv
  args:
    creates: /opt/app/venv

- name: Install Python requirements
  command: /opt/app/venv/bin/pip install -r /opt/app/requirements.txt
  args:
    chdir: /opt/app

- name: Copy Gunicorn systemd service file
  copy:
    src: gunicorn.service
    dest: /etc/systemd/system/gunicorn.service

- name: Reload systemd daemon
  command: systemctl daemon-reexec

- name: Enable and start Gunicorn service
  systemd:
    name: gunicorn
    enabled: yes
    state: restarted


- name: Start Flask app with Gunicorn (temporary)
  shell: |
    nohup /opt/app/venv/bin/gunicorn -w 4 -b 0.0.0.0:80 app:app &
  args:
    chdir: /opt/app

- name: Restart Gunicorn
  shell: |
    pkill gunicorn || true
    nohup /opt/app/venv/bin/gunicorn -w 4 -b 0.0.0.0:80 app:app &
  args:
    chdir: /opt/app

- name: Copy Nginx config template
  template:
    src: nginx_flask.j2
    dest: /etc/nginx/sites-available/flaskapp
    mode: '0644'

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable Flask Nginx site
  file:
    src: /etc/nginx/sites-available/flaskapp
    dest: /etc/nginx/sites-enabled/flaskapp
    state: link
    force: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Create MySQL database
  mysql_db:
    name: epadb
    state: present

- name: Create MySQL user
  mysql_user:
    name: user
    password: password
    priv: 'epadb.*:ALL'
    host: localhost
    state: present
